lab_1/urls.py
from django.urls import path
from .views import index
from .views import friend_list
urlpatterns = [
    path('', index, name='index'),
    # TODO Add friends path using friend_list Views
    path('friends',friend_list)
]

lab_2/urls.py
from django.urls import path
from .views import index
from .views import xml
from .views import json
urlpatterns = [
    path('', index, name='index'),
    path('xml', xml, name='xml'),
    path('json', json, name='json')
]

lab_3/urls.py
from django.urls import path
from .views import add_friend, index
urlpatterns = [
    path('',index, name='index'),
    path('add', add_friend)
]

lab_4/urls.py
from django.urls import path
from .views import index, add_note, note_list

app_name = "lab_4"
urlpatterns = [
    path('', index, name='index'),
    path('add-note', add_note),
    path('note-list', note_list)
]

praktikum/urls.py
from django.urls import path, re_path
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_3.urls as lab_3
import lab_4.urls as lab_4
from lab_1.views import index as index_lab1
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab-1/', include(lab_1)),
    path('lab-2/', include(lab_2)),
    path('lab-3/', include(lab_3)),
    path('lab-4/', include(lab_4)),
    re_path(r'^$', index_lab1, name='index')

]

lab_1/models.py
from django.db import models

# TODO Create Friend model that contains name, npm, and DOB (date of birth) here


class Friend(models.Model):
    name = models.CharField(max_length=30)
    # TODO Implement missing attributes in Friend model
    npm = models.CharField(max_length=10) #diganti dari bigInteger ke charfield 
    DOB = models.DateField()

lab_2/models.py
from django.db import models

# Create your models here.
class Note(models.Model):
    to = models.CharField(max_length=30)
    From = models.CharField(max_length=30)
    title = models.CharField(max_length=30)
    message = models.CharField(max_length=100)

lab_3/models.py
from django.db import models

# Create your models here.

lab_4/models.py
from django.db import models

# Create your models here.

lab_3/forms.py
from django import forms
from lab_1.models import Friend
class FriendForm(forms.ModelForm) :
    class Meta :
        model = Friend;
        fields = ['name','npm','DOB']
    
    input_attrs = {
        'name' : {
            'type' : 'text',
            'placeholder' : 'Masukkan nama'
        },
        'npm' : {
            'type' : 'text',
            'placeholder' : 'Masukkan npm'
        },
        'DOB' : {
            'type' :'date',
        }
        
    }
    
    name = forms.CharField(required=True, max_length=30, widget=forms.TextInput(attrs = input_attrs['name']))
    npm = forms.CharField(required= True, max_length=10, widget=forms.TextInput(attrs = input_attrs['npm']))
    DOB = forms.DateField(required=True, widget=forms.DateInput(attrs = input_attrs['DOB']))
        

lab_4/forms.py
from django import forms
from lab_2.models import Note

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note;
        fields = ['to','From','title','message']
    input_attrs = {
        'to' : {
            'type' : 'text',
            'placeholder': 'To'
        },
        'From' : {
            'type' : 'text',
            'placeholder': 'From'
        },
        'title': {
            'type' : 'text',
            'placeholder': 'Title'
        },
        'message': {
            'rows':'5',
            'cols' : '50',
            'placeholder': 'Message..'
        }
    }
    to = forms.CharField(required=True, max_length=30, widget=forms.TextInput(attrs = input_attrs['to']))
    From = forms.CharField(required=True, max_length=30, widget=forms.TextInput(attrs = input_attrs['From']))
    title = forms.CharField(required=True, max_length=30, widget=forms.TextInput(attrs = input_attrs['title']))
    message = forms.CharField(required=True, max_length=100, widget=forms.Textarea(attrs = input_attrs['message']))

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
from .models import Friend

mhs_name = 'Mochammad Agus Yahya'  # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(2001,12,23)  # TODO Implement this, format (Year, Month, Date)
npm = 2006596150  # TODO Implement this


def index(request):
    response = {'name': mhs_name,
                'age': calculate_age(birth_date.year),
                'npm': npm}
    return render(request, 'index_lab1.html', response)


def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0


def friend_list(request):
    friends = Friend.objects.all().values()  # TODO Implement this
    response = {'friends': friends}
    return render(request, 'friend_list_lab1.html', response)

lab_2/views.py
from django.http.response import HttpResponse
from django.core import serializers
from django.shortcuts import render
from .models import Note
# Create your views here.
def index(request):
    notes = Note.objects.all().values()
    response = {'notes' : notes}
    return render(request, 'lab2.html',response)
    
def xml(request):
    data = serializers.serialize('xml', Note.objects.all())
    return HttpResponse(data, content_type="application/xml")
def json(request):
    data = serializers.serialize('json', Note.objects.all())
    return HttpResponse(data, content_type="application/json")

lab_3/views.py
from django.shortcuts import render
from django.http.response import HttpResponseRedirect
from lab_1.models import Friend
from django.contrib.auth.decorators import login_required
from .forms import FriendForm
# Create your views here.

@login_required(login_url='/admin/login/')
def index(request):
    friends = Friend.objects.all().values()  # TODO Implement this
    response = {'friends': friends}
    return render(request, 'lab3_index.html', response)
    
@login_required(login_url='/admin/login/')
def add_friend(request):
    response ={}
    form = FriendForm(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return HttpResponseRedirect('/lab-3')
    response['form']= form
    return render(request, "lab3_form.html", response)
    
    

lab_4/views.py
from django.shortcuts import render
from django.http.response import HttpResponseRedirect
from lab_2.models import Note
from .forms import NoteForm
# Create your views here.

def index(request):
    notes = Note.objects.all().values()
    response = {'notes': notes}
    return render(request, 'lab4_index.html',response)

def add_note(request):
    form = NoteForm(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return HttpResponseRedirect('/lab-4')
    response = {'form' : form}
    return render(request, 'lab4_form.html',response)

def note_list(request):
    notes = Note.objects.all().values()
    response = {'notes':notes}
    return render(request,'lab4_note_list.html',response)

lab_1/templates/friend_list_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
    <style>
      table, td, th {
        border: 1px solid black;
      }
      
      table {
        border-collapse: collapse;
        width: 500px;
      }
      
      td {
        text-align: center;
      }
      </style>
  </head>
  <body>
    <table>
      <tr>
        <th>Name</th>
        <th>NPM</th>
        <th>DOB</th>
      </tr>
      <!-- TODO loop from Friend model -->
      {% if friends %} 
        {% for friend in friends %}
          <tr>
            <td>{{friend.name}}</td>
            <td>{{friend.npm}}</td>
            <td>{{friend.DOB}}</td>
          </tr>
        {% endfor %}
      {% endif %}
      <!-- EXAMPLE SECTION -->
      <!--
      <tr>
        <td>Asmara Nugi</td>
        <td>1706032156</td>
        <td>May 1, 1999</td>
      </tr>
      <tr>
        <td>Fadli Rais</td>
        <td>1706032370</td>
        <td>Sept 11, 1998</td>
      </tr>-->
      <!-- END SECTION -->
    </table>
  </body>
</html>

lab_1/templates/index_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{{ name }}</title>
  </head>
  <body>
    <h1>Hello my name is {{ name }}</h1>
    <article>NPM : {{ npm }}</article>
    <article>I am {{ age }} years old</article>
  </body>
</html>

lab_2/templates/lab2.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>Note</title>
        <style>
            table, td, th {
              border: 1px solid black;
            }
            
            table {
              border-collapse: collapse;
              width: 500px;
            }
            
            td {
              text-align: center;
            }
            </style>
    </head>
    <body>
        <table>
            <tr>
                <th>to</th>
                <th>from</th>
                <th>title</th>
                <th>message</th>
            </tr>
            {% if notes %} 
                {% for note in notes %}
                    <tr>
                        <td>{{note.to}}</td>
                        <td>{{note.From}}</td>
                        <td>{{note.title}}</td>
                        <td>{{note.message}}</td>
                    </tr>
                {% endfor %}
            {% endif %}
        </table>
    </body>
</html>

lab_3/templates/lab3_form.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title>Form</title>
    </head>
    <body>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="SUBMIT">
        </form>
    </body>
</html>

lab_3/templates/lab3_index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
    <style>
      table, td, th {
        border: 1px solid black;
      }
      
      table {
        border-collapse: collapse;
        width: 500px;
      }
      
      td {
        text-align: center;
      }
      </style>
  </head>
  <body>
    <table>
      <tr>
        <th>Name</th>
        <th>NPM</th>
        <th>DOB</th>
      </tr>
      <!-- TODO loop from Friend model -->
      {% if friends %} 
        {% for friend in friends %}
          <tr>
            <td>{{friend.name}}</td>
            <td>{{friend.npm}}</td>
            <td>{{friend.DOB}}</td>
          </tr>
        {% endfor %}
      {% endif %}
      <!-- EXAMPLE SECTION -->
      <!--
      <tr>
        <td>Asmara Nugi</td>
        <td>1706032156</td>
        <td>May 1, 1999</td>
      </tr>
      <tr>
        <td>Fadli Rais</td>
        <td>1706032370</td>
        <td>Sept 11, 1998</td>
      </tr>-->
      <!-- END SECTION -->
    </table>
  </body>
</html>

lab_4/templates/lab4_form.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Note Form</title>
        <link rel="stylesheet" href="{% static 'css/lab4_form.css' %}" type="text/css">
    </head>
    <body>
        <nav>
            <a href="{% url 'lab_4:index' %}">HOME</a>
            <a href="/lab-4/add-note">FORM</a>
            <a href="/lab-4/note-list">CARD</a>
        </nav>
        <h1>NOTE FORM</h1>
        <form action="" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input class="submit" type="submit" value="SUBMIT">
        </form>
    </body>
</html>

lab_4/templates/lab4_index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="UTF-8" />
        <title>Note</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/lab4_index.css' %}">
    </head>
    <body>
        <nav>
            <a href="/lab-4">HOME</a>
            <a href="/lab-4/add-note">FORM</a>
            <a href="/lab-4/note-list">CARD</a>
        </nav>
        <h1>NOTE</h1>
        <table>
            <tr>
                <th>to</th>
                <th>from</th>
                <th>title</th>
                <th>message</th>
            </tr>
            {% if notes %} 
                {% for note in notes %}
                    <tr>
                        <td>{{note.to}}</td>
                        <td>{{note.From}}</td>
                        <td>{{note.title}}</td>
                        <td class="message">{{note.message}}</td>
                    </tr>
                {% endfor %}
            {% endif %}
        </table>
    </body>
</html>

lab_4/templates/lab4_note_list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title>Note Card</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/lab4_note_list.css' %}">
    </head>
    <body>
        <nav>
            <a href="/lab-4">HOME</a>
            <a href="/lab-4/add-note">FORM</a>
            <a href="/lab-4/note-list">CARD</a>
        </nav>
        <h1 class="main">NOTE CARD</h1>
        {% for note in notes %}
        <div class="note">
            <h2 class="title">{{note.title}}</h2>
            <p class="to">Dear {{note.to}},</p>
            <p class="message">{{note.message}}</p>
            <p class="From">Regards,</p>
            <p class="From">{{note.From}}</p>
        </div>
        {% endfor %}
    </body>
</html>